### ISSUE TITLE
Lint SDP files

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-lint-scripts#11]
Follow up to https://github.com/AMWA-TV/nmos-render-scripts/issues/46

We should lint SDP files as well as JSON examples...

https://github.com/AMWA-TV/nmos-lint-scripts/blob/c816468672488e4d6eaf9d4541df5e36c2c131e4/lint.sh#L44-L52

Could use SDPoker?

**Comment by peterbrightwell** [comment]
Yes, see linked PR #12 which uses AMWA-TV's fork of SDPoker.  I've tested it briefly on my mac.
