### ISSUE TITLE
Lint examples in subdirectories

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-lint-scripts#3]
Needed for IS-08.

Cf. https://github.com/AMWA-TV/nmos-doc-build-scripts/commit/269b2341de69965519685f2023632e307d91d6b1

**Comment by peterbrightwell** [comment]
Looks to work at least for IS-08 (tested on Mac, GNU bash, v5.0.11 installed via homebrew -- MacOS system bash is still at v3.2 and doesn't have globstar).
